package openapi

import (
	"encoding/json"
	"slices"
	"strings"
	"testing"

	"github.com/tamnd/dbrest/backend"
	"github.com/tamnd/dbrest/ir"
	"github.com/tamnd/dbrest/rpc"
	"github.com/tamnd/dbrest/schema"
)

// filmsModel is a two-relation model: a films table with a primary key and a
// directors table films references by foreign key.
func filmsModel() *schema.Model {
	films := &schema.Relation{
		Name: "films",
		Kind: schema.KindTable,
		Columns: []*schema.Column{
			{Name: "id", Type: "integer", Nullable: false, Position: 1},
			{Name: "title", Type: "text", Nullable: false, Position: 2},
			{Name: "year", Type: "integer", Nullable: true, Position: 3},
			{Name: "director_id", Type: "integer", Nullable: true, Position: 4},
		},
		PrimaryKey: []string{"id"},
		ForeignKeys: []*schema.ForeignKey{
			{Name: "films_director_id_fkey", Columns: []string{"director_id"}, RefRelation: "directors", RefColumns: []string{"id"}},
		},
	}
	directors := &schema.Relation{
		Name: "directors",
		Kind: schema.KindTable,
		Columns: []*schema.Column{
			{Name: "id", Type: "integer", Nullable: false, Position: 1},
			{Name: "name", Type: "text", Nullable: false, Position: 2},
		},
		PrimaryKey: []string{"id"},
	}
	return schema.NewModel([]*schema.Relation{films, directors})
}

// sqliteCaps mirrors the SQLite backend's grades: regex and full-text present,
// array/range operators unsupported.
func sqliteCaps() backend.Capabilities {
	return backend.Capabilities{
		Regex:           backend.Native,
		FullText:        backend.FTSQLite5,
		IsDistinctFrom:  backend.Native,
		ArrayRangeTypes: backend.Unsupported,
	}
}

// decode generates the document and unmarshals it for structural assertions.
func decode(t *testing.T, model *schema.Model, fns rpc.Registry, caps backend.Capabilities, opts Options) map[string]any {
	t.Helper()
	body, err := Generate(model, fns, caps, opts)
	if err != nil {
		t.Fatalf("Generate: %v", err)
	}
	var doc map[string]any
	if err := json.Unmarshal(body, &doc); err != nil {
		t.Fatalf("unmarshal: %v", err)
	}
	return doc
}

func TestGenerateShape(t *testing.T) {
	doc := decode(t, filmsModel(), nil, sqliteCaps(), Options{Host: "localhost:3000"})
	if doc["swagger"] != "2.0" {
		t.Errorf("swagger = %v, want 2.0", doc["swagger"])
	}
	info := doc["info"].(map[string]any)
	if info["title"] != "PostgREST API" || info["version"] != "14.0" {
		t.Errorf("info = %v, want the v14 defaults", info)
	}
	if info["description"] != "This is a dynamic API generated by PostgREST" {
		t.Errorf("info description = %v", info["description"])
	}
	if doc["host"] != "localhost:3000" {
		t.Errorf("host = %v", doc["host"])
	}
	paths := doc["paths"].(map[string]any)
	if _, ok := paths["/films"]; !ok {
		t.Error("missing /films path")
	}
	if _, ok := paths["/directors"]; !ok {
		t.Error("missing /directors path")
	}
}

// TestInfoFromSchemaComment checks a provided title/description (sourced from
// the active schema's database comment) replaces the v14 defaults.
func TestInfoFromSchemaComment(t *testing.T) {
	doc := decode(t, filmsModel(), nil, sqliteCaps(), Options{Title: "Films API", Description: "All the films."})
	info := doc["info"].(map[string]any)
	if info["title"] != "Films API" || info["description"] != "All the films." {
		t.Errorf("info = %v", info)
	}
}

// TestDocumentFraming pins the v14 framing: externalDocs pointing at the
// PostgREST reference, the vendor media types in the top-level consumes and
// produces, and the "/" entry describing the root itself.
func TestDocumentFraming(t *testing.T) {
	doc := decode(t, filmsModel(), nil, sqliteCaps(), Options{})

	ed, ok := doc["externalDocs"].(map[string]any)
	if !ok {
		t.Fatal("missing externalDocs")
	}
	if ed["description"] != "PostgREST Documentation" {
		t.Errorf("externalDocs description = %v", ed["description"])
	}
	if ed["url"] != "https://postgrest.org/en/v14/references/api.html" {
		t.Errorf("externalDocs url = %v", ed["url"])
	}

	want := []string{
		"application/json",
		"application/vnd.pgrst.object+json;nulls=stripped",
		"application/vnd.pgrst.object+json",
		"text/csv",
	}
	for _, key := range []string{"consumes", "produces"} {
		got := doc[key].([]any)
		if len(got) != len(want) {
			t.Fatalf("%s = %v", key, got)
		}
		for i := range want {
			if got[i] != want[i] {
				t.Errorf("%s[%d] = %v, want %v", key, i, got[i], want[i])
			}
		}
	}

	root, ok := doc["paths"].(map[string]any)["/"].(map[string]any)
	if !ok {
		t.Fatal(`missing the "/" path entry`)
	}
	get := root["get"].(map[string]any)
	if get["summary"] != "OpenAPI description (this document)" {
		t.Errorf("root summary = %v", get["summary"])
	}
	tags := get["tags"].([]any)
	if len(tags) != 1 || tags[0] != "Introspection" {
		t.Errorf("root tags = %v", tags)
	}
	produces := get["produces"].([]any)
	if len(produces) != 2 || produces[0] != "application/openapi+json" || produces[1] != "application/json" {
		t.Errorf("root produces = %v", produces)
	}
}

// TestReservedParametersMatchV14 pins the shared parameter definitions against
// the live v14 document: names, locations, descriptions, enums, and the
// explicit required:false.
func TestReservedParametersMatchV14(t *testing.T) {
	doc := decode(t, filmsModel(), nil, sqliteCaps(), Options{})
	params := doc["parameters"].(map[string]any)

	cases := map[string]map[string]any{
		"select":       {"name": "select", "in": "query", "description": "Filtering Columns"},
		"on_conflict":  {"name": "on_conflict", "in": "query", "description": "On Conflict"},
		"order":        {"name": "order", "in": "query", "description": "Ordering"},
		"range":        {"name": "Range", "in": "header", "description": "Limiting and Pagination"},
		"rangeUnit":    {"name": "Range-Unit", "in": "header", "description": "Limiting and Pagination", "default": "items"},
		"offset":       {"name": "offset", "in": "query", "description": "Limiting and Pagination"},
		"limit":        {"name": "limit", "in": "query", "description": "Limiting and Pagination"},
		"preferParams": {"name": "Prefer", "in": "header", "description": "Preference"},
		"preferReturn": {"name": "Prefer", "in": "header", "description": "Preference",
			"enum": []any{"return=representation", "return=minimal", "return=none"}},
		"preferCount": {"name": "Prefer", "in": "header", "description": "Preference",
			"enum": []any{"count=none"}},
		"preferPost": {"name": "Prefer", "in": "header", "description": "Preference",
			"enum": []any{"return=representation", "return=minimal", "return=none", "resolution=ignore-duplicates", "resolution=merge-duplicates"}},
	}
	for key, want := range cases {
		got, ok := params[key].(map[string]any)
		if !ok {
			t.Errorf("missing parameter %q", key)
			continue
		}
		if got["type"] != "string" {
			t.Errorf("%s type = %v, want string", key, got["type"])
		}
		if req, present := got["required"]; !present || req != false {
			t.Errorf("%s required = %v, want explicit false", key, req)
		}
		for f, v := range want {
			if f == "enum" {
				gotEnum := got["enum"].([]any)
				wantEnum := v.([]any)
				if len(gotEnum) != len(wantEnum) {
					t.Errorf("%s enum = %v, want %v", key, gotEnum, wantEnum)
					continue
				}
				for i := range wantEnum {
					if gotEnum[i] != wantEnum[i] {
						t.Errorf("%s enum[%d] = %v, want %v", key, i, gotEnum[i], wantEnum[i])
					}
				}
				continue
			}
			if got[f] != v {
				t.Errorf("%s %s = %v, want %v", key, f, got[f], v)
			}
		}
	}
}

// TestRelationOperationLayout pins each table operation's parameter reference
// sequence and responses against the v14 layout: GET is rowFilters then the
// read block with a 200-array-schema and a 206; POST is body/select/preferPost
// with a 201; PATCH is rowFilters/body/preferReturn and DELETE
// rowFilters/preferReturn, both 204.
func TestRelationOperationLayout(t *testing.T) {
	doc := decode(t, filmsModel(), nil, sqliteCaps(), Options{})
	films := doc["paths"].(map[string]any)["/films"].(map[string]any)

	filterRefs := []string{
		"#/parameters/rowFilter.films.id",
		"#/parameters/rowFilter.films.title",
		"#/parameters/rowFilter.films.year",
		"#/parameters/rowFilter.films.director_id",
	}
	refSeq := func(op string) []string {
		params := films[op].(map[string]any)["parameters"].([]any)
		out := make([]string, len(params))
		for i, p := range params {
			out[i], _ = p.(map[string]any)["$ref"].(string)
		}
		return out
	}
	assertSeq := func(op string, want []string) {
		t.Helper()
		got := refSeq(op)
		if strings.Join(got, " ") != strings.Join(want, " ") {
			t.Errorf("%s parameters = %v, want %v", op, got, want)
		}
	}

	assertSeq("get", append(append([]string{}, filterRefs...),
		"#/parameters/select", "#/parameters/order", "#/parameters/range", "#/parameters/rangeUnit",
		"#/parameters/offset", "#/parameters/limit", "#/parameters/preferCount"))
	assertSeq("post", []string{"#/parameters/body.films", "#/parameters/select", "#/parameters/preferPost"})
	assertSeq("patch", append(append([]string{}, filterRefs...),
		"#/parameters/body.films", "#/parameters/preferReturn"))
	assertSeq("delete", append(append([]string{}, filterRefs...), "#/parameters/preferReturn"))

	get := films["get"].(map[string]any)
	resp := get["responses"].(map[string]any)
	ok200 := resp["200"].(map[string]any)
	schema200 := ok200["schema"].(map[string]any)
	if schema200["type"] != "array" {
		t.Errorf("200 schema type = %v, want array", schema200["type"])
	}
	if schema200["items"].(map[string]any)["$ref"] != "#/definitions/films" {
		t.Errorf("200 schema items = %v", schema200["items"])
	}
	if resp["206"].(map[string]any)["description"] != "Partial Content" {
		t.Errorf("206 = %v", resp["206"])
	}
	for op, want := range map[string]string{"post": "201", "patch": "204", "delete": "204"} {
		r := films[op].(map[string]any)["responses"].(map[string]any)
		if len(r) != 1 {
			t.Errorf("%s responses = %v, want only %s", op, r, want)
		}
		if _, ok := r[want]; !ok {
			t.Errorf("%s responses lack %s", op, want)
		}
	}

	// The shared body parameter names the table and references its definition.
	body := doc["parameters"].(map[string]any)["body.films"].(map[string]any)
	if body["name"] != "films" || body["in"] != "body" || body["description"] != "films" {
		t.Errorf("body.films = %v", body)
	}
	if body["schema"].(map[string]any)["$ref"] != "#/definitions/films" {
		t.Errorf("body.films schema = %v", body["schema"])
	}
}

func TestTableHasFullOperationSet(t *testing.T) {
	doc := decode(t, filmsModel(), nil, sqliteCaps(), Options{})
	films := doc["paths"].(map[string]any)["/films"].(map[string]any)
	for _, op := range []string{"get", "post", "patch", "delete"} {
		if _, ok := films[op]; !ok {
			t.Errorf("/films missing %s operation", op)
		}
	}
}

func TestViewIsReadOnly(t *testing.T) {
	rel := &schema.Relation{
		Name: "v_films", Kind: schema.KindView,
		Columns: []*schema.Column{{Name: "title", Type: "text", Position: 1}},
	}
	doc := decode(t, schema.NewModel([]*schema.Relation{rel}), nil, sqliteCaps(), Options{})
	v := doc["paths"].(map[string]any)["/v_films"].(map[string]any)
	if _, ok := v["get"]; !ok {
		t.Error("view should have get")
	}
	for _, op := range []string{"post", "patch", "delete"} {
		if _, ok := v[op]; ok {
			t.Errorf("read-only view should not have %s", op)
		}
	}
}

func TestDefinitionTypesAndRequired(t *testing.T) {
	doc := decode(t, filmsModel(), nil, sqliteCaps(), Options{})
	films := doc["definitions"].(map[string]any)["films"].(map[string]any)
	props := films["properties"].(map[string]any)

	id := props["id"].(map[string]any)
	if id["type"] != "integer" || id["format"] != "integer" {
		t.Errorf("id = %v, want integer/integer", id)
	}
	if !strings.Contains(id["description"].(string), "Note:\nThis is a Primary Key.<pk/>") {
		t.Errorf("id description = %v, want the v14 PK marker", id["description"])
	}
	title := props["title"].(map[string]any)
	if title["type"] != "string" || title["format"] != "text" {
		t.Errorf("title = %v, want string/text", title)
	}
	// required = every NOT NULL column in column order, as v14 lists them.
	req := films["required"].([]any)
	got := make([]string, len(req))
	for i, c := range req {
		got[i] = c.(string)
	}
	if strings.Join(got, ",") != "id,title" {
		t.Errorf("required = %v, want [id title]", got)
	}
}

// TestRequiredIncludesDefaultedColumns pins the v14 quirk: a NOT NULL column
// stays in required even when it has a default (live 14.12 lists serial PKs).
func TestRequiredIncludesDefaultedColumns(t *testing.T) {
	rel := &schema.Relation{
		Name: "items", Kind: schema.KindTable,
		Columns: []*schema.Column{
			{Name: "id", Type: "integer", Nullable: false, HasDefault: true, Position: 1},
			{Name: "label", Type: "text", Nullable: false, Position: 2},
			{Name: "note", Type: "text", Nullable: true, Position: 3},
		},
		PrimaryKey: []string{"id"},
	}
	doc := decode(t, schema.NewModel([]*schema.Relation{rel}), nil, sqliteCaps(), Options{})
	items := doc["definitions"].(map[string]any)["items"].(map[string]any)
	req := items["required"].([]any)
	got := make([]string, len(req))
	for i, c := range req {
		got[i] = c.(string)
	}
	if strings.Join(got, ",") != "id,label" {
		t.Errorf("required = %v, want [id label]", got)
	}
}

func TestForeignKeyNote(t *testing.T) {
	doc := decode(t, filmsModel(), nil, sqliteCaps(), Options{})
	props := doc["definitions"].(map[string]any)["films"].(map[string]any)["properties"].(map[string]any)
	fk := props["director_id"].(map[string]any)
	desc, _ := fk["description"].(string)
	if !strings.Contains(desc, "Note:\nThis is a Foreign Key to `directors.id`.<fk table='directors' column='id'/>") {
		t.Errorf("director_id description = %q, want the v14 FK marker", desc)
	}
}

// rowFilterDesc resolves a column's rowFilter parameter through the shared
// parameters map, the way a client follows the $ref an operation carries.
func rowFilterDesc(t *testing.T, doc map[string]any, table, col string) string {
	t.Helper()
	params, ok := doc["parameters"].(map[string]any)
	if !ok {
		t.Fatal("document has no parameters map")
	}
	p, ok := params["rowFilter."+table+"."+col].(map[string]any)
	if !ok {
		t.Fatalf("no rowFilter.%s.%s parameter found", table, col)
	}
	if p["name"] != col || p["in"] != "query" || p["type"] != "string" {
		t.Errorf("rowFilter.%s.%s = %v", table, col, p)
	}
	if req, present := p["required"]; !present || req != false {
		t.Errorf("rowFilter.%s.%s required = %v, want explicit false", table, col, req)
	}
	desc, _ := p["description"].(string)
	return desc
}

// TestOperatorAdvertisingHonorsCapabilities is the heart of the contract: a
// column parameter advertises match/imatch and the fts family on SQLite (regex
// and FTS5 present) but never the array/range operators (Unsupported).
func TestOperatorAdvertisingHonorsCapabilities(t *testing.T) {
	doc := decode(t, filmsModel(), nil, sqliteCaps(), Options{})
	colDesc := rowFilterDesc(t, doc, "films", "title")
	if colDesc == "" {
		t.Fatal("title rowFilter parameter has no description")
	}
	for _, want := range []string{"eq", "match", "imatch", "fts", "plfts", "phfts", "wfts"} {
		if !containsToken(colDesc, want) {
			t.Errorf("operator %q should be advertised; desc = %q", want, colDesc)
		}
	}
	for _, gone := range []string{"cs", "cd", "ov", "sl", "sr", "adj"} {
		if containsToken(colDesc, gone) {
			t.Errorf("operator %q should be omitted on SQLite; desc = %q", gone, colDesc)
		}
	}
}

// TestRegexOmittedWhenUnsupported drops match/imatch when the backend grades
// regex Unsupported, proving the advertising is driven by the matrix.
func TestRegexOmittedWhenUnsupported(t *testing.T) {
	caps := sqliteCaps()
	caps.Regex = backend.Unsupported
	caps.FullText = backend.FTNone
	doc := decode(t, filmsModel(), nil, caps, Options{})
	desc := rowFilterDesc(t, doc, "films", "title")
	for _, gone := range []string{"match", "imatch", "fts"} {
		if containsToken(desc, gone) {
			t.Errorf("operator %q should be omitted; desc = %q", gone, desc)
		}
	}
}

func TestSecurityInactiveOmitsDefinitions(t *testing.T) {
	// PostgREST's default: with openapi-security-active off the document has
	// neither securityDefinitions nor a security requirement, even with JWT
	// auth configured on the server.
	doc := decode(t, filmsModel(), nil, sqliteCaps(), Options{})
	if _, ok := doc["securityDefinitions"]; ok {
		t.Error("securityDefinitions should be absent when security is inactive")
	}
	if _, ok := doc["security"]; ok {
		t.Error("security should be absent when security is inactive")
	}
}

func TestSecurityActiveEmitsJWTScheme(t *testing.T) {
	doc := decode(t, filmsModel(), nil, sqliteCaps(), Options{SecurityActive: true})
	sd, ok := doc["securityDefinitions"].(map[string]any)
	if !ok {
		t.Fatal("no securityDefinitions with security active")
	}
	jwt := sd["JWT"].(map[string]any)
	if jwt["type"] != "apiKey" || jwt["name"] != "Authorization" || jwt["in"] != "header" {
		t.Errorf("JWT scheme = %v", jwt)
	}
	if jwt["description"] != `Add the token prepending "Bearer " (without quotes) to it` {
		t.Errorf("JWT description = %v", jwt["description"])
	}
	// The requirement is document-level, the way v14 attaches it.
	sec, ok := doc["security"].([]any)
	if !ok || len(sec) != 1 {
		t.Fatalf("security = %v, want one document-level requirement", doc["security"])
	}
	if _, ok := sec[0].(map[string]any)["JWT"]; !ok {
		t.Errorf("security requirement = %v, want JWT", sec[0])
	}
	// Operations carry no per-operation security in v14.
	get := doc["paths"].(map[string]any)["/films"].(map[string]any)["get"].(map[string]any)
	if _, attached := get["security"]; attached {
		t.Error("security should not be attached per operation")
	}
}

func TestRPCPaths(t *testing.T) {
	reg := rpc.NewStaticRegistry([]*rpc.Function{
		{
			Name:       "add",
			Params:     []rpc.Param{{Name: "a", Type: "int4"}, {Name: "b", Type: "int4"}},
			Returns:    rpc.ReturnShape{Kind: rpc.ReturnScalar, Type: "int4"},
			Volatility: rpc.Immutable,
		},
		{
			Name:       "log_event",
			Params:     []rpc.Param{{Name: "msg", Type: "text"}},
			Returns:    rpc.ReturnShape{Kind: rpc.ReturnScalar, Type: "void"},
			Volatility: rpc.Volatile,
		},
	})
	doc := decode(t, filmsModel(), reg, sqliteCaps(), Options{})
	paths := doc["paths"].(map[string]any)

	add, ok := paths["/rpc/add"].(map[string]any)
	if !ok {
		t.Fatal("missing /rpc/add")
	}
	if _, ok := add["get"]; !ok {
		t.Error("immutable function should be callable by GET")
	}
	post, ok := add["post"].(map[string]any)
	if !ok {
		t.Fatal("function should be callable by POST")
	}

	// v14 tags rpc operations "(rpc) <name>" and drops text/csv from produces.
	tags := post["tags"].([]any)
	if len(tags) != 1 || tags[0] != "(rpc) add" {
		t.Errorf("rpc tags = %v, want [(rpc) add]", tags)
	}
	produces := post["produces"].([]any)
	for _, mt := range produces {
		if mt == "text/csv" {
			t.Error("rpc produces should not list text/csv")
		}
	}
	if len(produces) != 3 || produces[0] != "application/json" {
		t.Errorf("rpc produces = %v", produces)
	}

	// POST takes the args as one required body plus the preferParams ref; GET
	// inlines one query parameter per argument.
	postParams := post["parameters"].([]any)
	if len(postParams) != 2 {
		t.Fatalf("rpc post parameters = %v", postParams)
	}
	args := postParams[0].(map[string]any)
	if args["name"] != "args" || args["in"] != "body" || args["required"] != true {
		t.Errorf("rpc args parameter = %v", args)
	}
	if postParams[1].(map[string]any)["$ref"] != "#/parameters/preferParams" {
		t.Errorf("rpc post parameters[1] = %v", postParams[1])
	}
	getParams := add["get"].(map[string]any)["parameters"].([]any)
	if len(getParams) != 2 {
		t.Fatalf("rpc get parameters = %v", getParams)
	}
	for i, name := range []string{"a", "b"} {
		p := getParams[i].(map[string]any)
		if p["name"] != name || p["in"] != "query" || p["required"] != true {
			t.Errorf("rpc get parameter %d = %v", i, p)
		}
	}

	logEvent, ok := paths["/rpc/log_event"].(map[string]any)
	if !ok {
		t.Fatal("missing /rpc/log_event")
	}
	if _, ok := logEvent["get"]; ok {
		t.Error("volatile function should not be callable by GET")
	}
	if _, ok := logEvent["post"]; !ok {
		t.Error("volatile function should be callable by POST")
	}
}

// commentedModel is a films table annotated the way COMMENT ON does it: a
// two-line relation comment, a column comment on title, none elsewhere.
func commentedModel() *schema.Model {
	rel := &schema.Relation{
		Name: "films", Kind: schema.KindTable,
		Comment: "The films catalog\nEvery film we know about, one row each.",
		Columns: []*schema.Column{
			{Name: "id", Type: "integer", Nullable: false, Position: 1},
			{Name: "title", Type: "text", Nullable: false, Position: 2, Comment: "Original release title"},
		},
		PrimaryKey: []string{"id"},
	}
	return schema.NewModel([]*schema.Relation{rel})
}

// TestRelationCommentAnnotatesOperations pins the v14 comment pipeline on a
// relation: the first comment line becomes every operation's summary, the
// rest the description, and the definition and body parameter carry the full
// comment.
func TestRelationCommentAnnotatesOperations(t *testing.T) {
	doc := decode(t, commentedModel(), nil, sqliteCaps(), Options{})
	films := doc["paths"].(map[string]any)["/films"].(map[string]any)
	for _, op := range []string{"get", "post", "patch", "delete"} {
		o := films[op].(map[string]any)
		if o["summary"] != "The films catalog" {
			t.Errorf("%s summary = %v", op, o["summary"])
		}
		if o["description"] != "Every film we know about, one row each." {
			t.Errorf("%s description = %v", op, o["description"])
		}
	}
	def := doc["definitions"].(map[string]any)["films"].(map[string]any)
	if def["description"] != "The films catalog\nEvery film we know about, one row each." {
		t.Errorf("definition description = %v", def["description"])
	}
	body := doc["parameters"].(map[string]any)["body.films"].(map[string]any)
	if body["description"] != "The films catalog\nEvery film we know about, one row each." {
		t.Errorf("body.films description = %v", body["description"])
	}
}

// TestUncommentedOperationsStayBare checks an uncommented relation emits no
// summary or description at all, matching v14's omission.
func TestUncommentedOperationsStayBare(t *testing.T) {
	doc := decode(t, filmsModel(), nil, sqliteCaps(), Options{})
	get := doc["paths"].(map[string]any)["/films"].(map[string]any)["get"].(map[string]any)
	if _, ok := get["summary"]; ok {
		t.Errorf("summary should be omitted, got %v", get["summary"])
	}
	if _, ok := get["description"]; ok {
		t.Errorf("description should be omitted, got %v", get["description"])
	}
}

// TestColumnCommentInPropertyAndRowFilter pins the column comment's two
// surfaces: ahead of the key notes in the definition property, and ahead of
// the operator advertisement in the rowFilter parameter.
func TestColumnCommentInPropertyAndRowFilter(t *testing.T) {
	rel := &schema.Relation{
		Name: "films", Kind: schema.KindTable,
		Columns: []*schema.Column{
			{Name: "id", Type: "integer", Nullable: false, Position: 1, Comment: "the film identifier"},
		},
		PrimaryKey: []string{"id"},
	}
	doc := decode(t, schema.NewModel([]*schema.Relation{rel}), nil, sqliteCaps(), Options{})

	prop := doc["definitions"].(map[string]any)["films"].(map[string]any)["properties"].(map[string]any)["id"].(map[string]any)
	if prop["description"] != "the film identifier\n\nNote:\nThis is a Primary Key.<pk/>" {
		t.Errorf("property description = %q", prop["description"])
	}

	desc := rowFilterDesc(t, doc, "films", "id")
	if !strings.HasPrefix(desc, "the film identifier\n\n") {
		t.Errorf("rowFilter description = %q, want the comment first", desc)
	}
	if !containsToken(desc, "eq") {
		t.Errorf("rowFilter description lost the operator list: %q", desc)
	}
}

// TestFunctionCommentAnnotatesRPC pins the same split on an rpc path, sourced
// from the registry declaration's comment field.
func TestFunctionCommentAnnotatesRPC(t *testing.T) {
	reg := rpc.NewStaticRegistry([]*rpc.Function{{
		Name:       "add",
		Comment:    "Add two numbers\nReturns the sum of a and b.",
		Params:     []rpc.Param{{Name: "a", Type: "int4"}, {Name: "b", Type: "int4"}},
		Returns:    rpc.ReturnShape{Kind: rpc.ReturnScalar, Type: "int4"},
		Volatility: rpc.Immutable,
	}})
	doc := decode(t, filmsModel(), reg, sqliteCaps(), Options{})
	add := doc["paths"].(map[string]any)["/rpc/add"].(map[string]any)
	for _, op := range []string{"get", "post"} {
		o := add[op].(map[string]any)
		if o["summary"] != "Add two numbers" {
			t.Errorf("%s summary = %v", op, o["summary"])
		}
		if o["description"] != "Returns the sum of a and b." {
			t.Errorf("%s description = %v", op, o["description"])
		}
	}
}

// TestDeterministic checks the same inputs marshal byte-for-byte the same, so a
// cached document and a regenerated one match.
func TestDeterministic(t *testing.T) {
	a, _ := Generate(filmsModel(), nil, sqliteCaps(), Options{Host: "h"})
	b, _ := Generate(filmsModel(), nil, sqliteCaps(), Options{Host: "h"})
	if string(a) != string(b) {
		t.Error("generation is not deterministic")
	}
}

func TestOperatorTierResolution(t *testing.T) {
	caps := sqliteCaps()
	if operatorTier(ir.OpEq, caps) != backend.Native {
		t.Error("eq should be Native")
	}
	if operatorTier(ir.OpMatch, caps) != backend.Native {
		t.Error("match should follow Regex tier")
	}
	if operatorTier(ir.OpFTS, caps) != backend.BestEffort {
		t.Error("fts should be BestEffort on FTS5")
	}
	if operatorTier(ir.OpContains, caps).OK() {
		t.Error("cs should be Unsupported when ArrayRangeTypes is Unsupported")
	}
	// An explicit per-operator override wins over the feature class.
	caps.Operators = map[int]backend.Tier{int(ir.OpMatch): backend.Unsupported}
	if operatorTier(ir.OpMatch, caps).OK() {
		t.Error("explicit override should make match Unsupported")
	}
}

func BenchmarkGenerate(b *testing.B) {
	model := filmsModel()
	caps := sqliteCaps()
	b.ReportAllocs()
	for b.Loop() {
		if _, err := Generate(model, nil, caps, Options{Host: "localhost:3000"}); err != nil {
			b.Fatal(err)
		}
	}
}

// containsToken reports whether desc lists op as a comma-separated operator
// token, so "cs" does not match inside "docs" and "sr" does not match "string".
func containsToken(desc, op string) bool {
	_, list, ok := strings.Cut(desc, "Operators: ")
	if !ok {
		return false
	}
	list = strings.TrimSuffix(strings.TrimSpace(list), ".")
	return slices.Contains(strings.Split(list, ", "), op)
}
