// Package openapi generates the self-describing root PostgREST emits at GET /.
// The document is a Swagger 2.0 (OpenAPI) description of every exposed relation
// and function, built from the unified schema model and the RPC registry and
// served with the application/openapi+json media type.
//
// The generator is part of the frontend: it reads the already-built model and
// the backend's declared capabilities, never an engine catalog. The same model
// produces the same document on every backend, so the document's structure is
// portable; only the type precision tracks how exact the model is. See spec 19.
package openapi

import (
	"encoding/json"
	"strings"

	"github.com/tamnd/dbrest/backend"
	"github.com/tamnd/dbrest/ir"
	"github.com/tamnd/dbrest/pgtypes"
	"github.com/tamnd/dbrest/rpc"
	"github.com/tamnd/dbrest/schema"
)

// MediaType is the content type PostgREST serves the root with.
const MediaType = "application/openapi+json"

// docsURL is the externalDocs target, the v14 PostgREST reference the emitted
// document points at, matching the live v14 output byte for byte.
const docsURL = "https://postgrest.org/en/v14/references/api.html"

// bodyMediaTypes is the top-level consumes and produces list v14 advertises:
// JSON, the singular-object vendor types, and CSV.
var bodyMediaTypes = []string{
	"application/json",
	"application/vnd.pgrst.object+json;nulls=stripped",
	"application/vnd.pgrst.object+json",
	"text/csv",
}

// rpcMediaTypes is the per-operation produces list on /rpc paths; v14 leaves
// CSV off there.
var rpcMediaTypes = []string{
	"application/json",
	"application/vnd.pgrst.object+json;nulls=stripped",
	"application/vnd.pgrst.object+json",
}

// Options configures the emitted document's identity, server block, and
// security. The host/basePath/schemes are the externally visible address (the
// listen address, or the proxy URL once that configuration lands, spec 20).
type Options struct {
	// Title and Description are the info block, sourced from the active
	// schema's database comment when one exists (first line and remainder);
	// the defaults are the strings v14 emits for an uncommented schema.
	Title       string
	Description string

	Version  string   // info.version; defaults to the compat target "14.0"
	Host     string   // host:port the API is reached at
	BasePath string   // mount path; defaults to "/"
	Schemes  []string // url schemes; defaults to ["http"]

	// ActiveSchema is the schema the document describes: the request's
	// profile-negotiated schema, so a multi-schema deployment serves one
	// document per schema and same-named relations never collide on a path key.
	ActiveSchema string

	// Visibility filters the document for openapi-mode=follow-privileges: it
	// answers which operations the requesting role may perform on a relation,
	// and a relation with none is dropped from paths and definitions, so an
	// anonymous caller cannot enumerate what it cannot touch. Nil emits
	// everything, the ignore-privileges mode.
	Visibility func(rel *schema.Relation) Actions

	// SecurityActive is the PostgREST openapi-security-active setting (spec
	// 20): when true the document carries the JWT securityDefinitions block
	// and a document-level security requirement; when false (the default)
	// neither is emitted, exactly as v14 behaves regardless of whether JWT
	// auth is configured.
	SecurityActive bool
}

// Actions is the operation set a role holds on one relation, the visibility
// answer follow-privileges filters the document with.
type Actions struct {
	Get, Post, Patch, Delete bool
}

// AllActions marks every operation visible, the ignore-privileges answer.
var AllActions = Actions{Get: true, Post: true, Patch: true, Delete: true}

func (a Actions) any() bool { return a.Get || a.Post || a.Patch || a.Delete }

func (o Options) withDefaults() Options {
	if o.Title == "" {
		o.Title = "PostgREST API"
	}
	if o.Description == "" {
		o.Description = "This is a dynamic API generated by PostgREST"
	}
	if o.Version == "" {
		o.Version = "14.0"
	}
	if o.BasePath == "" {
		o.BasePath = "/"
	}
	if len(o.Schemes) == 0 {
		o.Schemes = []string{"http"}
	}
	return o
}

// Generate builds the OpenAPI document for the model and returns it as the JSON
// bytes the root serves. The capabilities decide which filter operators each
// column advertises, so the document never promises a feature the next request
// would reject with PGRST127.
func Generate(model *schema.Model, fns rpc.Registry, caps backend.Capabilities, opts Options) ([]byte, error) {
	return json.MarshalIndent(build(model, fns, caps, opts), "", "  ")
}

// build assembles the document struct. It is separated from Generate so a test
// can assert on the structure without reparsing JSON.
func build(model *schema.Model, fns rpc.Registry, caps backend.Capabilities, opts Options) *document {
	opts = opts.withDefaults()
	doc := &document{
		Swagger:      "2.0",
		Info:         info{Title: opts.Title, Description: opts.Description, Version: opts.Version},
		Host:         opts.Host,
		BasePath:     opts.BasePath,
		Schemes:      opts.Schemes,
		Consumes:     bodyMediaTypes,
		Produces:     bodyMediaTypes,
		Paths:        map[string]*pathItem{"/": rootPath()},
		Definitions:  map[string]*schemaObject{},
		Parameters:   reservedParameters(),
		ExternalDocs: &externalDocs{Description: "PostgREST Documentation", URL: docsURL},
	}

	ops := advertisedTokens(caps)
	if opts.SecurityActive {
		doc.SecurityDefinitions = map[string]*securityScheme{
			"JWT": {Type: "apiKey", Name: "Authorization", In: "header",
				Description: `Add the token prepending "Bearer " (without quotes) to it`},
		}
		doc.Security = []map[string][]string{{"JWT": {}}}
	}

	for _, rel := range model.RelationsIn(opts.ActiveSchema) {
		acts := AllActions
		if opts.Visibility != nil {
			acts = opts.Visibility(rel)
		}
		if rel.Kind == schema.KindView {
			// A view path carries only get; a write-only grant leaves nothing
			// to describe.
			acts.Post, acts.Patch, acts.Delete = false, false, false
		}
		if !acts.any() {
			continue
		}
		doc.Paths["/"+rel.Name] = relationPath(rel, acts)
		doc.Definitions[rel.Name] = relationDefinition(rel)
		addRelationParameters(doc.Parameters, rel, ops)
	}
	if fns != nil {
		for _, fn := range fns.List() {
			doc.Paths["/rpc/"+fn.Name] = functionPath(fn)
		}
	}
	return doc
}

// rootPath is the "/" entry describing the root itself, byte-identical to the
// block v14 emits.
func rootPath() *pathItem {
	return &pathItem{Get: &operation{
		Tags:      []string{"Introspection"},
		Summary:   "OpenAPI description (this document)",
		Produces:  []string{"application/openapi+json", "application/json"},
		Responses: map[string]*response{"200": {Description: "OK"}},
	}}
}

// relationPath emits the operations a relation supports, each one referencing
// the shared rowFilter.<table>.<col> and body.<table> parameter definitions
// the way v14 lays them out. A base table gets the full read/write set; a
// view gets get only (updatable views land with the model flags that mark
// them so). The acts set drops any operation the requesting role may not
// perform.
func relationPath(rel *schema.Relation, acts Actions) *pathItem {
	filters := rowFilterRefs(rel)
	body := refs("body." + rel.Name)
	p := &pathItem{}
	if acts.Get {
		p.Get = &operation{
			Tags:       []string{rel.Name},
			Parameters: concat(filters, refs("select", "order", "range", "rangeUnit", "offset", "limit", "preferCount")),
			Responses: map[string]*response{
				"200": {Description: "OK", Schema: &schemaObject{
					Type:  "array",
					Items: &schemaObject{Ref: "#/definitions/" + rel.Name},
				}},
				"206": {Description: "Partial Content"},
			},
		}
	}
	if rel.Kind == schema.KindTable {
		if acts.Post {
			p.Post = &operation{
				Tags:       []string{rel.Name},
				Parameters: concat(body, refs("select", "preferPost")),
				Responses:  okResponses("201", "Created"),
			}
		}
		if acts.Patch {
			p.Patch = &operation{
				Tags:       []string{rel.Name},
				Parameters: concat(filters, body, refs("preferReturn")),
				Responses:  okResponses("204", "No Content"),
			}
		}
		if acts.Delete {
			p.Delete = &operation{
				Tags:       []string{rel.Name},
				Parameters: concat(filters, refs("preferReturn")),
				Responses:  okResponses("204", "No Content"),
			}
		}
	}
	return p
}

// relationDefinition builds the schema object for a relation from its columns.
// A property's type/format comes from the column's canonical type; required
// lists every non-nullable column in column order (a column with a default is
// still required, matching v14); the primary key and foreign keys surface in
// the property descriptions the way PostgREST annotates them.
func relationDefinition(rel *schema.Relation) *schemaObject {
	def := &schemaObject{Type: "object", Properties: map[string]*propertySchema{}}
	pk := map[string]bool{}
	for _, c := range rel.PrimaryKey {
		pk[c] = true
	}
	for _, col := range rel.Columns {
		typ, format := swaggerType(col.Type)
		prop := &propertySchema{Type: typ, Format: format}
		prop.Description = columnNote(col.Name, pk, rel.ForeignKeys)
		def.Properties[col.Name] = prop
		if !col.Nullable {
			def.Required = append(def.Required, col.Name)
		}
	}
	return def
}

// functionPath emits the /rpc/<fn> path with v14's layout: the "(rpc) <name>"
// tag, the JSON-only produces list, a POST whose args body is always required
// followed by the preferParams reference, and a GET with inline query
// parameters for a read-only function (stable or immutable); a volatile
// function is POST only. See spec 12.
func functionPath(fn *rpc.Function) *pathItem {
	p := &pathItem{}
	if fn.Volatility.ReadOnly() {
		p.Get = &operation{
			Tags:       []string{"(rpc) " + fn.Name},
			Produces:   rpcMediaTypes,
			Parameters: functionQueryParams(fn),
			Responses:  okResponses("200", "OK"),
		}
	}
	p.Post = &operation{
		Tags:     []string{"(rpc) " + fn.Name},
		Produces: rpcMediaTypes,
		Parameters: concat(
			[]*parameter{{In: "body", Name: "args", Required: boolPtr(true), Schema: functionBodySchema(fn)}},
			refs("preferParams"),
		),
		Responses: okResponses("200", "OK"),
	}
	return p
}

func functionQueryParams(fn *rpc.Function) []*parameter {
	out := make([]*parameter, 0, len(fn.Params))
	for _, pm := range fn.Params {
		typ, format := swaggerType(pm.Type)
		out = append(out, &parameter{Name: pm.Name, In: "query", Required: boolPtr(!pm.Optional), Type: typ, Format: format})
	}
	return out
}

func functionBodySchema(fn *rpc.Function) *schemaObject {
	s := &schemaObject{Type: "object", Properties: map[string]*propertySchema{}}
	for _, pm := range fn.Params {
		typ, format := swaggerType(pm.Type)
		s.Properties[pm.Name] = &propertySchema{Type: typ, Format: format}
		if !pm.Optional {
			s.Required = append(s.Required, pm.Name)
		}
	}
	return s
}

// addRelationParameters defines the shared per-relation parameters operations
// reference: one rowFilter.<table>.<col> per column and, for a table, the
// body.<table> payload. The rowFilter description carries the operator
// grammar the backend can actually serve, dbrest's capability advertisement
// (spec 19); v14 leaves the field empty, so the addition is tooling-safe.
func addRelationParameters(params map[string]*parameter, rel *schema.Relation, ops string) {
	for _, col := range rel.Columns {
		params["rowFilter."+rel.Name+"."+col.Name] = &parameter{
			Name:        col.Name,
			In:          "query",
			Required:    boolPtr(false),
			Type:        "string",
			Description: ops,
		}
	}
	if rel.Kind == schema.KindTable {
		params["body."+rel.Name] = &parameter{
			Name:        rel.Name,
			In:          "body",
			Required:    boolPtr(false),
			Description: rel.Name,
			Schema:      &schemaObject{Ref: "#/definitions/" + rel.Name},
		}
	}
}

// rowFilterRefs lists the relation's rowFilter references in column order, the
// horizontal-filter block every read and filtered write starts with.
func rowFilterRefs(rel *schema.Relation) []*parameter {
	out := make([]*parameter, 0, len(rel.Columns))
	for _, col := range rel.Columns {
		out = append(out, &parameter{Ref: "#/parameters/rowFilter." + rel.Name + "." + col.Name})
	}
	return out
}

// advertisedTokens lists the filter operators a column may use, in a stable
// order, omitting any operator the backend grades Unsupported. The text is the
// shared description every column parameter carries (spec 19).
func advertisedTokens(caps backend.Capabilities) string {
	var toks []string
	for _, e := range operatorOrder {
		if operatorTier(e.op, caps).OK() {
			toks = append(toks, e.token)
		}
	}
	return "Horizontal filter. Format: col=op.value. Operators: " + strings.Join(toks, ", ") + "."
}

var operatorOrder = []struct {
	token string
	op    ir.Op
}{
	{"eq", ir.OpEq}, {"neq", ir.OpNeq},
	{"gt", ir.OpGt}, {"gte", ir.OpGte}, {"lt", ir.OpLt}, {"lte", ir.OpLte},
	{"like", ir.OpLike}, {"ilike", ir.OpILike},
	{"match", ir.OpMatch}, {"imatch", ir.OpIMatch},
	{"in", ir.OpIn}, {"is", ir.OpIs}, {"isdistinct", ir.OpIsDistinct},
	{"fts", ir.OpFTS}, {"plfts", ir.OpFTS}, {"phfts", ir.OpFTS}, {"wfts", ir.OpFTS},
	{"cs", ir.OpContains}, {"cd", ir.OpContained}, {"ov", ir.OpOverlap},
	{"sl", ir.OpRangeSL}, {"sr", ir.OpRangeSR},
	{"nxr", ir.OpRangeNXR}, {"nxl", ir.OpRangeNXL}, {"adj", ir.OpRangeAdj},
}

// operatorTier resolves the governing capability tier for one operator. An
// explicit per-operator override in the matrix wins; otherwise the operator
// inherits the tier of the feature class it belongs to (regex, full-text,
// array/range, is-distinct), and the plain comparison operators are Native
// everywhere.
func operatorTier(op ir.Op, caps backend.Capabilities) backend.Tier {
	if caps.Operators != nil {
		if t, ok := caps.Operators[int(op)]; ok {
			return t
		}
	}
	switch op {
	case ir.OpMatch, ir.OpIMatch:
		return caps.Regex
	case ir.OpFTS:
		if caps.FullText == backend.FTNone {
			return backend.Unsupported
		}
		if caps.FullText == backend.FTTSVector {
			return backend.Native
		}
		return backend.BestEffort
	case ir.OpIsDistinct:
		return caps.IsDistinctFrom
	case ir.OpContains, ir.OpContained, ir.OpOverlap,
		ir.OpRangeSL, ir.OpRangeSR, ir.OpRangeNXR, ir.OpRangeNXL, ir.OpRangeAdj:
		return caps.ArrayRangeTypes
	default:
		return backend.Native
	}
}

// swaggerType maps a canonical (or engine-aliased) type name to the Swagger
// type and format pair. The format is the model's own type name, so it carries
// exactly the precision the engine offered, no finer (spec 19, "limits").
func swaggerType(canonical string) (typ, format string) {
	if canonical == "" {
		return "string", ""
	}
	switch pgtypes.ClassOf(canonical) {
	case pgtypes.ClassInteger:
		return "integer", canonical
	case pgtypes.ClassFloat, pgtypes.ClassNumeric:
		return "number", canonical
	case pgtypes.ClassBool:
		return "boolean", canonical
	default:
		return "string", canonical
	}
}

// columnNote builds the PostgREST property annotation: a primary-key note, a
// foreign-key note, or both. Each note carries the machine-readable <pk/> or
// <fk table='...' column='...'/> marker tooling parses out of the v14
// documents. An unannotated column gets an empty description.
func columnNote(name string, pk map[string]bool, fks []*schema.ForeignKey) string {
	var notes []string
	if pk[name] {
		notes = append(notes, "Note:\nThis is a Primary Key.<pk/>")
	}
	for _, fk := range fks {
		for i, c := range fk.Columns {
			if c != name {
				continue
			}
			ref := fk.RefRelation
			col := ""
			if i < len(fk.RefColumns) {
				col = fk.RefColumns[i]
				ref += "." + col
			}
			notes = append(notes,
				"Note:\nThis is a Foreign Key to `"+ref+"`.<fk table='"+fk.RefRelation+"' column='"+col+"'/>")
		}
	}
	return strings.Join(notes, "\n")
}

// reservedParameters defines the shared parameters operations reference by
// $ref. Names, descriptions, and enums match the v14 document exactly,
// including the on_conflict entry that is defined without being referenced.
func reservedParameters() map[string]*parameter {
	return map[string]*parameter{
		"select":      {Name: "select", In: "query", Required: boolPtr(false), Type: "string", Description: "Filtering Columns"},
		"on_conflict": {Name: "on_conflict", In: "query", Required: boolPtr(false), Type: "string", Description: "On Conflict"},
		"order":       {Name: "order", In: "query", Required: boolPtr(false), Type: "string", Description: "Ordering"},
		"range":       {Name: "Range", In: "header", Required: boolPtr(false), Type: "string", Description: "Limiting and Pagination"},
		"rangeUnit":   {Name: "Range-Unit", In: "header", Required: boolPtr(false), Type: "string", Description: "Limiting and Pagination", Default: "items"},
		"offset":      {Name: "offset", In: "query", Required: boolPtr(false), Type: "string", Description: "Limiting and Pagination"},
		"limit":       {Name: "limit", In: "query", Required: boolPtr(false), Type: "string", Description: "Limiting and Pagination"},
		"preferParams": {Name: "Prefer", In: "header", Required: boolPtr(false), Type: "string",
			Description: "Preference"},
		"preferReturn": {Name: "Prefer", In: "header", Required: boolPtr(false), Type: "string",
			Description: "Preference", Enum: []string{"return=representation", "return=minimal", "return=none"}},
		"preferCount": {Name: "Prefer", In: "header", Required: boolPtr(false), Type: "string",
			Description: "Preference", Enum: []string{"count=none"}},
		"preferPost": {Name: "Prefer", In: "header", Required: boolPtr(false), Type: "string",
			Description: "Preference", Enum: []string{"return=representation", "return=minimal", "return=none", "resolution=ignore-duplicates", "resolution=merge-duplicates"}},
	}
}

func boolPtr(b bool) *bool { return &b }

func refs(names ...string) []*parameter {
	out := make([]*parameter, len(names))
	for i, n := range names {
		out[i] = &parameter{Ref: "#/parameters/" + n}
	}
	return out
}

func concat(groups ...[]*parameter) []*parameter {
	var out []*parameter
	for _, g := range groups {
		out = append(out, g...)
	}
	return out
}

func okResponses(code, desc string) map[string]*response {
	return map[string]*response{code: {Description: desc}}
}
